version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: disaster_postgis
    environment:
      POSTGRES_DB: disaster_db
      POSTGRES_USER: disaster_user
      POSTGRES_PASSWORD: disaster_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
